version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/data
    environment:
      - FLASK_ENV=production
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      # Replace <YOUR_PUBLIC_IP> with your EC2 public IP
      - REACT_APP_API_URL=http://<13.61.177.172>:5000
    networks:
      - app_network

volumes:
  backend_data:

networks:
  app_network:
    driver: bridge

