version: "3.9"

services:
  # ===============================
  # Backend (FastAPI)
  # ===============================
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    volumes:
      - backend_data:/app/data
    networks:
      - app_network
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # ===============================
  # Frontend
  # ===============================
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  # ===============================
  # Prometheus
  # ===============================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  # ===============================
  # Node Exporter
  # ===============================
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    restart: always
    command:
      - '--path.rootfs=/host'
    pid: "host"
    volumes:
      - /:/host:ro,rslave

  # ===============================
  # Grafana
  # ===============================
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana

  # ===============================
  # Jenkins
  # ===============================
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - monitoring
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 30s
      timeout: 10s
      retries: 5

# ===============================
# Volumes
# ===============================
volumes:
  backend_data:
  prometheus_data:
  grafana_data:
  jenkins_data:

# ===============================
# Networks
# ===============================
networks:
  app_network:
    driver: bridge
  monitoring:
    driver: bridge
