
version: '3.8'

services:
  ###############################################
  # 🧠 BACKEND SERVICE
  ###############################################
  backend:
    image: your-dockerhub-username/fusionpact-backend:${BUILD_NUMBER:-latest}
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
    networks:
      - monitoring
      - app_net

  ###############################################
  # 🎨 FRONTEND SERVICE
  ###############################################
  frontend:
    image: your-dockerhub-username/fusionpact-frontend:${BUILD_NUMBER:-latest}
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080
    networks:
      - app_net

  ###############################################
  # ⚙️ PROMETHEUS
  ###############################################
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    depends_on:
      - backend
      - jenkins

  ###############################################
  # 📊 GRAFANA
  ###############################################
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - monitoring

  ###############################################
  # 🧱 NODE EXPORTER (SYSTEM METRICS)
  ###############################################
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring

  ###############################################
  # 🧰 JENKINS
  ###############################################
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring

networks:
  app_net:
  monitoring:

volumes:
  jenkins_data:
