
services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/data
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

volumes:
  backend_data:

networks:
  app_network:
    driver: bridge


